apiVersion: 1
datasources:
  - name: Prometheus-datasource-1
    type: prometheus
    url: http://prometheus:9091
    access: proxy
    isDefault: true
  - name: Prometheus-datasource-2
    type: prometheus
    url: http://prometheus:9091
    access: proxy
    isDefault: false
